// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCqajVJyYvEfBXhyzwR0lcCnKTWVXNlFrQ',
    appId: '1:138784060440:web:535edc043be723a675ff6d',
    messagingSenderId: '138784060440',
    projectId: 'formal-loop-429615-s3',
    authDomain: 'formal-loop-429615-s3.firebaseapp.com',
    storageBucket: 'formal-loop-429615-s3.firebasestorage.app',
    measurementId: 'G-ENCMW7ZQ5Q',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDJgvyy-F4E6d0PWZKI9NTnsDMzdUkkXFU',
    appId: '1:138784060440:android:332dae9d2e19dc9675ff6d',
    messagingSenderId: '138784060440',
    projectId: 'formal-loop-429615-s3',
    storageBucket: 'formal-loop-429615-s3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBCGG9LtJBfpM9z3NtkIft-Y4KlZW_OgTM',
    appId: '1:138784060440:ios:37b00d3c4452856d75ff6d',
    messagingSenderId: '138784060440',
    projectId: 'formal-loop-429615-s3',
    storageBucket: 'formal-loop-429615-s3.firebasestorage.app',
    iosBundleId: 'com.example.examenmada',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBCGG9LtJBfpM9z3NtkIft-Y4KlZW_OgTM',
    appId: '1:138784060440:ios:37b00d3c4452856d75ff6d',
    messagingSenderId: '138784060440',
    projectId: 'formal-loop-429615-s3',
    storageBucket: 'formal-loop-429615-s3.firebasestorage.app',
    iosBundleId: 'com.example.examenmada',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCqajVJyYvEfBXhyzwR0lcCnKTWVXNlFrQ',
    appId: '1:138784060440:web:916d6d0b0c47519275ff6d',
    messagingSenderId: '138784060440',
    projectId: 'formal-loop-429615-s3',
    authDomain: 'formal-loop-429615-s3.firebaseapp.com',
    storageBucket: 'formal-loop-429615-s3.firebasestorage.app',
    measurementId: 'G-F6K3FGLTXN',
  );
}
